export const ADICIONAR_USER = 'ADICIONAR_USER';
export const ADICIONAR_SENHA = 'ADICIONAR_SENHA';
export const LOADING_EXIBIR = 'LOADING_EXIBIR';
export const LOADING_OCULTAR = 'LOADING_OCULTAR';
export const LOGIN_LOGAR = 'LOGIN_LOGAR';
