export const ADD_USER = 'ADD_USER';
export const ADD_PASSWORD = 'ADD_PASSWORD'
export const LOADING_EXIBIR = 'LOADING_EXIBIR';
export const LOADING_OCULTAR = 'LOADING_OCULTAR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
